version: '3.8'

services:
  backend:
    ports:
      - 8888:8888
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    environment:
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=123
    volumes:
      - ./backend:/backend
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
